"""create reviews and findings tables

Revision ID: c2d2a28bf414
Revises: 
Create Date: 2026-08-17 01:16:09.931069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d2a28bf414'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='reviewstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity'), nullable=False),
    sa.Column('category', sa.Enum('security', 'style', 'logic', 'tests', name='category'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('static', 'llm', name='source'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('reviews')
    # ### end Alembic commands ###
